### ISSUE TITLE
Legal OSS compliance question 

### ISSUE THREAD

**Issue by ajopjo** [cp79shark/Shark.PdfConvert#11]
Since this framework use WkHtmlToPdf  and WkHtmlToPdf  is under LGPLv3 which is a heavy copy left license, can this FW be licensed under MIT? I know its not directly distributing WkHtmlToPdf  as part of the distro package, however to make use of the package a developer needs WkHtmlToPdf .

**Comment by cp79shark** [comment]
IANAL, but a quick google should satisfy your question.

https://softwareengineering.stackexchange.com/questions/141847/how-does-using-a-lgpl-gem-affect-my-mit-licensed-application

https://opensource.stackexchange.com/questions/7904/can-your-mit-library-use-an-lgpl-library
