### ISSUE TITLE
Is there a global settings for PdfConversionSettings.PdfToolPath?

### ISSUE THREAD

**Issue by ThisNoName** [cp79shark/Shark.PdfConvert#12]
Or anything else in the  PdfConversionSettings  for that matter?  Like adding a logo on all generated document.

Since PdfConvert is global static, it seems making sense to have global settings as well?

Thanks.

**Comment by cp79shark** [comment]
I guess I don't follow on what you mean by global. I assume you mean the shape of the API isn't intuitive for you? There are various `Custom**Args` properties on `PdfConversionSettings` that you can set for the more advanced use cases.

If you want to modify anything, please feel free to submit a PR and I'll review it (faster than I responded to this issue, sorry...).

I had started a refactor (builder pattern, sensible defaults, etc) of the whole project, but with moving and a new job and everything just haven't been able to allocate time for it. Also, haven't found the flash drive it was on (probably in an unpacked box, heh).

Again, sorry for the delay.

**Comment by ThisNoName** [comment]
Thanks for the update.  It's really trivial stuff, for example, 

- I have wkhtmltopdf.exe in a custom location, but too lazy to set it every time
- Maybe there's a custom section I want to add to all document generated

Wonder if it can be set once in startup and forget about.

    PdfConversionSettings.PdfToolPath = "wherever";

I have a workaround like this.

```
   public class MyPdfConversionSettings : PdfConversionSettings  {
        public MyPdfConversionSettings() {
            base.PdfToolPath = Path.Combine(
                Path.GetPathRoot(Environment.CurrentDirectory), 
                    "wkhtmltopdf", "wkhtmltopdf.exe");
```
Not really a big deal, whatever you planned.  Appreciate all the great work!

**Comment by cp79shark** [comment]
Well, shoot. I can't seem to find the work I've done on converting this library to the "builder" pattern. I would continue using what you have, if it's still a need for your project. If you still would like to submit a PR for anything, I'll get to it quicker now. Promise. Thanks for your patience.
