### ISSUE TITLE
not converting arabic language

### ISSUE THREAD

**Issue by Hamzaliaqat321** [cp79shark/Shark.PdfConvert#14]
i have an html that is in both languages english and arabic.
it properly converts english and desgin to PDF but arabic replaced by special characters
![Annotation 2020-09-10 102520](https://user-images.githubusercontent.com/62440774/92684908-041a7f00-f350-11ea-886c-aa69039ffc65.png)

**Comment by cp79shark** [comment]
Hi, this looks like an issue with wkhtmltopdf. This project is just a thin wrapper for that tool.

Here are some similar issues I found doing a quick search:

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3954
https://stackoverflow.com/a/17795727
https://www.api2pdf.com/multi-lingual-support-for-html-to-pdf-wkhtmltopdf-headless-chrome/

The common theme I notice is you need to ensure the proper arabic font is available with-in your HTML content.

If after trying some of the above you still think it's this library, please re-open and provide a small sample that can reproduce the issue. Thanks!.
