### ISSUE TITLE
PageWidth and PageHeight not working

### ISSUE THREAD

**Issue by defra91** [cp79shark/Shark.PdfConvert#15]
I need to create a pdf file with custom page width and height in mm.

I have tried to set in on the configuration but it seems not working. I have checked the source code and it seems that this parameter is not used on the rendering process of the pdf file.

Can you please provide support for it?

**Comment by rossdonald** [comment]
You could try using `CustomWkHtmlPageArgs` to set the page width and height 

```
var settings = new PdfConversionSettings
{
  //...
    CustomWkHtmlPageArgs = " --page-width 88mm --page-height 56mm";
};
```

Custom args mentioned here https://github.com/cp79shark/Shark.PdfConvert/issues/6#issuecomment-397319150

**Comment by cp79shark** [comment]
@defra91 `CustomWkHtmlPageArgs` should do the trick for you, as @rossdonald suggested. If not, please re-open the issue and we can come up with a better work around or bug fix for you. Thanks!

**Comment by rossdonald** [comment]
Well PageWidth and PageHeight were fixed just recently (here https://github.com/cp79shark/Shark.PdfConvert/commit/ae1a2e158965a2d55c562f1e7c645741cf47d0c9) so they should work now.

You shouldn't have to use the CustomArgs

**Comment by cp79shark** [comment]
Heh, It’s been one of those days. Yes, I merged that PR and published to Nuget earlier today. 1.0.4.
