### ISSUE TITLE
Problem with Zoom and Page Size settings

### ISSUE THREAD

**Issue by zejtin** [cp79shark/Shark.PdfConvert#5]
Hello,

I have a problem with zoom and page size settings i receive error from wkhtmltopdf, this is my config:

```
Shark.PdfConvert.PdfConversionSettings config = new Shark.PdfConvert.PdfConversionSettings
                    {
                        Title = "Converted by Shark.PdfConvert",
                        LowQuality = false,
                        Margins = new Shark.PdfConvert.PdfPageMargins() { Bottom = 10, Left = 10, Right = 10, Top = 10 },
                        Size = Shark.PdfConvert.PdfPageSize.A4,
                        Zoom = 1.2f,
                        OutputPath = @"C:\DATA\pdfSharkTest.pdf"
                    };

```
this is the error i receive:

**WkHTMLToPdf conversion of HTML data failed. Output: \r\nWkHTMLToPdf exited with code 1.**

am I using it wrong? :) without Zoom and Size options it generates file normally

**Comment by cp79shark** [comment]
No, you're not using it wrong. I had it wrong with where those options should go and a missing space in the configuration.

I have the code changes and added a test for those two options. Uploaded a new version to NuGet (1.0.3) and it should be visible shortly.

If that doesn't help let me know.

**Comment by zejtin** [comment]
Thank you for the fast fix, It works perfectly now!
