### ISSUE TITLE
pageto, page, etc. keywords are not being replaced 

### ISSUE THREAD

**Issue by JakobMoser** [cp79shark/Shark.PdfConvert#8]
Is it possible that the keyword replacer for <b>'frompage', 'topage', 'page', 'webpage', 'section', 'subsection', 'subsubsection'</b> is not working or not implemented correctly for the headerHtml and footerHtml. You know, where you should just type `<span class="page"></span>` and the inside the `<span>` there should be the page number. 

I fixed this by inserting the `subst()` JS script and calling it `onload` of `<body>` in my html-file like this. 

        ...
        <script>
            function subst() {
              var vars={};
              var x=document.location.search.substring(1).split('&');
              for (var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
              var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
              for (var i in x) {
                var y = document.getElementsByClassName(x[i]);
                for (var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
              }
            }
        </script>
    </head>

    <body onload="subst()">
     ...

Maybe this helps somebody.

**Comment by cp79shark** [comment]
I got bit by this before. The header and footer html have to be a *well formed* HTML document, not just a snippet. It's WkHtmlToPdf, not this wrapper that has that restriction.
